language: node_js
node_js:
  - '0.10'
  - '0.12'

cache:
  directories:
    - node_modules

branches:
  except:
    - gh-pages

# addons:
#   apt:
#     sources:
#       - rabbitmq-testing
#       - qpid-testing
#     packages:
#       - rabbitmq-server
#       - qpidd

before_script:
  - npm install -g codeclimate-test-reporter
  - sudo add-apt-repository ppa:qpid/testing -y
  - sudo apt-get update -q
  - sudo apt-get install qpidd qpid-tools
  - sudo sh -c 'echo "auth=no" >> /etc/qpid/qpidd.conf'
  - sudo /etc/init.d/qpidd restart

  # remove these when we can specify link properties
  - sudo qpid-config add queue test.disposition.queue

script:
  - make coverage
after_script:
  - make codeclimate-send

env:
  global:
    secure: "gvb+JTpIBa6AeZHJQuVVzTl3QOtuaVxKQQdezGJWYYwsw9UmVk30WjetXkeu0GNclnsNJtm+PfQp2sMYuQEOVy2zoHL+UQ6PkAk6yqaaHW/nOReKj6XLZZlGWx/4QRIofHw75IB6f81YFfZ+1jXsjVqo/YBXeGC2xsr0lMuB1w0="
    secure: "frXAbyNAV8BDoKZNQS5FD+rRnzqJ7/mBrz54Uo2WXU1+IkGBQ6PYMJh5Xn4sGktr0F9I7KXL7YKuN8311SFURjKV+3E54ySNYWF+tLtLDoEuHdcMGZbMsGm8b8aLurgZboDMIMQb5vfOG2fn+xnIhdUiDmL6/ZQQ6gKhCgjPsrw="
    secure: "wgt3LJSC/wIuL1SqQ4457z471QeSDNZgFVU/nUHR0prwXvKveiVkrk5PYTkUfjfQAwm1rfTiAXSz/2nvE937U1YmHNLcMqI9Hkh4STwPJMf0Zwn602DPKkZ5EkJU5oQU33AqwQQ/B/qXK0BdLmhSaMW8t+4PyVQ4ujaAoL0AaNY="
    secure: "OqOGpGVOUKffcDlQpFWlwWgC6nMZJk0pMXZV19kvFu/WTyIcQdhI+/D6IRfsL1GSbl+R/zvdBtDQMzeXrSPuFaP/lW392djYAGCTd6xrt2z4aPNI3CQ7x/rSPFCcgBlLIz2LD4/GCdPYHZUSr9jIlsEoxPJLwzL3A1X/o9wj/O4="
    secure: "VtsnwW4Xc87e8SxYRV1WJ0TmrvmcQY1vQUkHQveaWtvPtqCyZVBt+qwfXNLjk8+7Bkr+yIpv6zzP9oxQRSwZCZtpTfNe9AReb3l6cNKpsVZ1+z7JjO5fugwFwgBjMvdxaciy0TjLSr0IGi+r0vrMpwK5J5N1FcV0gqS4Y33QfQ4="
    secure: "GR1oBhmji5LJj0ZUAP0eom5+tM3Yy86ORrmV1qnnX/40KT4fAW85Z4St3JkzY4qdiZ7ZKW4kOmSiSOSGk/uSZXA/2RZR9euPE15OFg9AdqXj4lneuCq6zzAvhjP6ixpyOtyKGo6KRPTfKSRryZQAs3vsbRogPk+4XPOlcFEQofU="
    secure: "KuL30s0rh4usuw1NSc4BSmpkECGYIMqk+2+M/V4ZDrRV/JsSwwaN2Z1gW90RHmWXS+yc5gCsqWbC4yTAP35BsRdkrJtKhtV7SQAnKVoztGkLSe58lTWyfeSpREW8D4kXsTmVo6/sVutPne9amcOjY8q0McTzp+RrNgyAWc3Tn4E="
    secure: "CNLcU4sCSb2d3r98o2ASWPm+6heklnvIZGFwcMLXCr5o5b6tf3ydjSsinIWDm80AwIFyWHMdYbVXxwGQtLCS6rsuwJkZZMUqL9sgO3vMGanUqQdQbc19sQIp8qtwYk7ePsD0KUQxAsNv6eIoJ+yeBOq2EN0F46JsCeR5B6b1b6I="
