language: node_js

node_js:
  - "0.10"
  - "0.12"

sudo: false

addons:
  code_climate:
    repo_token: b33b8273d40cd973eaa72e274445544847dc4ed74447118765176eae6dd722cb

cache:
  directories:
    - node_modules

branches:
  except:
    - gh-pages

script:
  - make coverage

after_script:
  - cat coverage/lcov.info | codeclimate
